name: Publish Docs

on:
  workflow_dispatch:

jobs:

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Install C3
        run: |
          curl -L https://github.com/c3lang/c3c/releases/latest/download/c3-linux-static.tar.gz -o c3.tar.gz
          mkdir c3
          tar -xzf c3.tar.gz -C c3 --strip-components=1
          sudo mv c3 /opt/c3

          sudo ln -s /opt/c3/c3c /usr/local/bin/c3c

          c3c --version

      - name: Generate c3 docs
        run: bash ./scripts/c3_docgen.sh

      - name: Install Python documentation dependencies
        run: |
          python -m pip install uv
          uv sync --locked

      - name: Build MkDocs documentation
        run: uv run mkdocs build --strict

      - name: Upload docs artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: c3-docs
          path: docs.html
          archive: true

      - name: Upload MkDocs artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mkdocs-docs
          path: site
          archive: true

  publish-docs:
    runs-on: ubuntu-latest
    needs: [build-docs]
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: c3-docs
          path: docs

      - name: Download MkDocs artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: mkdocs-docs
          path: site

      - name: Prepare folder structure
        run: |
          mkdir -p pages/api-reference
          mkdir -p pages/mkdocs
          mv docs/docs.html pages/api-reference/index.html
          mv site/* pages/mkdocs/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        


